[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
colored = "2.1.0"
eyre = "0.6.12"
hashbag = "0.1.12"
itertools = "0.13.0"
num = "0.4.3"
petgraph = "0.6.5"
regex = "1.11.1"
